namespace:
  name: sandbox

image:
  repository: evigi/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  ports:
  - port: 4111
    protocol: TCP
    type: ClusterIP
    targetPort: 3111
resources:
    requests:
        memory: "64Mi"
        cpu: "250m"
    limits:
        memory: "128Mi"
        cpu: "500m"
ports: 
    containerPort: 3111
livelinessProbe:
    httpGet:
      path: /healthz
      port: 3111
readinessProbe:
    httpGet:
      path: /healthz
      port: 3111
